FROM node:7.10

# Install nodemon
RUN npm install -g nodemon

# Install forever
RUN npm install -g forever

# next several lines are for non-dev deployment
RUN mkdir /app

# Bundle app source - COPY command for a non-dev deployment, for dev we want the container to use files from
# a local directory so changes are propogated immediately
COPY ./ /app/

WORKDIR /app
RUN npm install
WORKDIR ./app-src
RUN npm install
RUN rm -R -f build
# RUN npm run build
WORKDIR ../

EXPOSE 80

ENTRYPOINT ["npm", "start"]